import type { AutomationGrade, TaskType } from './enums'

export interface ChannelDefinition {
  name: string
  displayName: string
  category: 'SEARCH_ENGINE' | 'LOCAL_DIRECTORY' | 'APP_STORE' | 'SOCIAL_MEDIA' | 'REVIEW_PLATFORM' | 'BLOG_PLATFORM' | 'BUSINESS_DIRECTORY' | 'MAP_SERVICE'
  description: string
  automationCapability: AutomationGrade
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
  requiredAssets: string[]
  supportedTaskTypes: TaskType[]
  // 채널 적합도 계산에 사용
  suitableServiceTypes: string[]
  suitableGoalTypes: string[]
}

export const CHANNEL_CATALOG: ChannelDefinition[] = [
  {
    name: 'google_business_profile',
    displayName: 'Google Business Profile',
    category: 'LOCAL_DIRECTORY',
    description: '구글 지도 및 검색에 비즈니스 정보를 노출하는 무료 도구',
    automationCapability: 'B',
    riskLevel: 'MEDIUM',
    requiredAssets: ['LOGO', 'IMAGE', 'TEXT'],
    supportedTaskTypes: ['CHANNEL_REGISTRATION', 'PROFILE_UPDATE', 'REVIEW_RESPONSE', 'INFO_SYNC', 'IMAGE_UPDATE', 'DESCRIPTION_UPDATE'],
    suitableServiceTypes: ['LOCAL_BUSINESS', 'ECOMMERCE', 'OTHER'],
    suitableGoalTypes: ['LOCAL_EXPOSURE_INCREASE', 'INQUIRY_INCREASE', 'REVIEW_MANAGEMENT', 'SEARCH_TRAFFIC_INCREASE'],
  },
  {
    name: 'naver_place',
    displayName: '네이버 플레이스',
    category: 'LOCAL_DIRECTORY',
    description: '네이버 지도에 매장/업체 정보를 등록하고 관리',
    automationCapability: 'C',
    riskLevel: 'MEDIUM',
    requiredAssets: ['LOGO', 'IMAGE', 'TEXT', 'DOCUMENT'],
    supportedTaskTypes: ['CHANNEL_REGISTRATION', 'PROFILE_UPDATE', 'REVIEW_RESPONSE', 'INFO_SYNC', 'IMAGE_UPDATE'],
    suitableServiceTypes: ['LOCAL_BUSINESS'],
    suitableGoalTypes: ['LOCAL_EXPOSURE_INCREASE', 'INQUIRY_INCREASE', 'REVIEW_MANAGEMENT'],
  },
  {
    name: 'naver_blog',
    displayName: '네이버 블로그',
    category: 'BLOG_PLATFORM',
    description: '네이버 검색 상위 노출을 위한 블로그 콘텐츠 운영',
    automationCapability: 'B',
    riskLevel: 'MEDIUM',
    requiredAssets: ['IMAGE', 'TEXT'],
    supportedTaskTypes: ['CONTENT_PUBLISH', 'SEO_OPTIMIZATION', 'DESCRIPTION_UPDATE'],
    suitableServiceTypes: ['WEB_SERVICE', 'LOCAL_BUSINESS', 'ECOMMERCE', 'CONTENT_PLATFORM', 'SAAS'],
    suitableGoalTypes: ['SEARCH_TRAFFIC_INCREASE', 'BRAND_AWARENESS', 'SIGNUP_INCREASE'],
  },
  {
    name: 'apple_app_store',
    displayName: 'Apple App Store',
    category: 'APP_STORE',
    description: 'iOS 앱 스토어 등록 및 최적화',
    automationCapability: 'C',
    riskLevel: 'HIGH',
    requiredAssets: ['LOGO', 'IMAGE', 'TEXT'],
    supportedTaskTypes: ['PROFILE_UPDATE', 'REVIEW_RESPONSE', 'IMAGE_UPDATE', 'DESCRIPTION_UPDATE', 'SEO_OPTIMIZATION'],
    suitableServiceTypes: ['MOBILE_APP'],
    suitableGoalTypes: ['APP_INSTALL_INCREASE', 'REVIEW_MANAGEMENT', 'BRAND_AWARENESS'],
  },
  {
    name: 'google_play_store',
    displayName: 'Google Play Store',
    category: 'APP_STORE',
    description: '안드로이드 앱 스토어 등록 및 최적화',
    automationCapability: 'C',
    riskLevel: 'HIGH',
    requiredAssets: ['LOGO', 'IMAGE', 'TEXT'],
    supportedTaskTypes: ['PROFILE_UPDATE', 'REVIEW_RESPONSE', 'IMAGE_UPDATE', 'DESCRIPTION_UPDATE', 'SEO_OPTIMIZATION'],
    suitableServiceTypes: ['MOBILE_APP'],
    suitableGoalTypes: ['APP_INSTALL_INCREASE', 'REVIEW_MANAGEMENT', 'BRAND_AWARENESS'],
  },
  {
    name: 'instagram',
    displayName: 'Instagram',
    category: 'SOCIAL_MEDIA',
    description: '비주얼 중심 소셜 미디어 마케팅',
    automationCapability: 'B',
    riskLevel: 'MEDIUM',
    requiredAssets: ['IMAGE', 'TEXT'],
    supportedTaskTypes: ['CONTENT_PUBLISH', 'PROFILE_UPDATE', 'IMAGE_UPDATE', 'DESCRIPTION_UPDATE'],
    suitableServiceTypes: ['WEB_SERVICE', 'LOCAL_BUSINESS', 'ECOMMERCE', 'CONTENT_PLATFORM', 'MOBILE_APP'],
    suitableGoalTypes: ['BRAND_AWARENESS', 'SIGNUP_INCREASE', 'LOCAL_EXPOSURE_INCREASE'],
  },
  {
    name: 'google_search_console',
    displayName: 'Google Search Console',
    category: 'SEARCH_ENGINE',
    description: '구글 검색 성과 모니터링 및 SEO 최적화',
    automationCapability: 'A',
    riskLevel: 'LOW',
    requiredAssets: ['TEXT'],
    supportedTaskTypes: ['MONITORING', 'SEO_OPTIMIZATION', 'INFO_SYNC'],
    suitableServiceTypes: ['WEB_SERVICE', 'ECOMMERCE', 'CONTENT_PLATFORM', 'SAAS'],
    suitableGoalTypes: ['SEARCH_TRAFFIC_INCREASE', 'SIGNUP_INCREASE'],
  },
  {
    name: 'naver_search_advisor',
    displayName: '네이버 서치어드바이저',
    category: 'SEARCH_ENGINE',
    description: '네이버 검색 등록 및 최적화',
    automationCapability: 'A',
    riskLevel: 'LOW',
    requiredAssets: ['TEXT'],
    supportedTaskTypes: ['MONITORING', 'SEO_OPTIMIZATION', 'INFO_SYNC'],
    suitableServiceTypes: ['WEB_SERVICE', 'ECOMMERCE', 'CONTENT_PLATFORM', 'SAAS', 'LOCAL_BUSINESS'],
    suitableGoalTypes: ['SEARCH_TRAFFIC_INCREASE', 'SIGNUP_INCREASE', 'LOCAL_EXPOSURE_INCREASE'],
  },
  {
    name: 'kakao_map',
    displayName: '카카오맵',
    category: 'MAP_SERVICE',
    description: '카카오맵에 업체 정보 등록 및 관리',
    automationCapability: 'C',
    riskLevel: 'MEDIUM',
    requiredAssets: ['LOGO', 'IMAGE', 'TEXT'],
    supportedTaskTypes: ['CHANNEL_REGISTRATION', 'PROFILE_UPDATE', 'INFO_SYNC', 'IMAGE_UPDATE'],
    suitableServiceTypes: ['LOCAL_BUSINESS'],
    suitableGoalTypes: ['LOCAL_EXPOSURE_INCREASE', 'INQUIRY_INCREASE'],
  },
  {
    name: 'youtube',
    displayName: 'YouTube',
    category: 'SOCIAL_MEDIA',
    description: '영상 콘텐츠 마케팅 및 브랜드 채널 운영',
    automationCapability: 'B',
    riskLevel: 'MEDIUM',
    requiredAssets: ['IMAGE', 'TEXT', 'VIDEO'],
    supportedTaskTypes: ['CONTENT_PUBLISH', 'PROFILE_UPDATE', 'DESCRIPTION_UPDATE', 'SEO_OPTIMIZATION'],
    suitableServiceTypes: ['WEB_SERVICE', 'MOBILE_APP', 'ECOMMERCE', 'CONTENT_PLATFORM', 'SAAS'],
    suitableGoalTypes: ['BRAND_AWARENESS', 'SIGNUP_INCREASE', 'APP_INSTALL_INCREASE'],
  },
  {
    name: 'facebook',
    displayName: 'Facebook',
    category: 'SOCIAL_MEDIA',
    description: '페이스북 비즈니스 페이지 운영',
    automationCapability: 'B',
    riskLevel: 'MEDIUM',
    requiredAssets: ['LOGO', 'IMAGE', 'TEXT'],
    supportedTaskTypes: ['CONTENT_PUBLISH', 'PROFILE_UPDATE', 'REVIEW_RESPONSE', 'DESCRIPTION_UPDATE', 'CTA_UPDATE'],
    suitableServiceTypes: ['WEB_SERVICE', 'LOCAL_BUSINESS', 'ECOMMERCE', 'CONTENT_PLATFORM', 'MOBILE_APP'],
    suitableGoalTypes: ['BRAND_AWARENESS', 'SIGNUP_INCREASE', 'INQUIRY_INCREASE', 'LOCAL_EXPOSURE_INCREASE'],
  },
  {
    name: 'naver_smart_store',
    displayName: '네이버 스마트스토어',
    category: 'BUSINESS_DIRECTORY',
    description: '네이버 쇼핑 입점 및 상품 관리',
    automationCapability: 'C',
    riskLevel: 'HIGH',
    requiredAssets: ['LOGO', 'IMAGE', 'TEXT', 'DOCUMENT'],
    supportedTaskTypes: ['CHANNEL_REGISTRATION', 'PROFILE_UPDATE', 'DESCRIPTION_UPDATE', 'IMAGE_UPDATE', 'REVIEW_RESPONSE'],
    suitableServiceTypes: ['ECOMMERCE'],
    suitableGoalTypes: ['SIGNUP_INCREASE', 'SEARCH_TRAFFIC_INCREASE', 'REVIEW_MANAGEMENT'],
  },
]
